#pragma once
#include <string>

std::string s[] {
    "jasldkjfaspl;djfa;sljg;ldfjgodwfhodfhldfadlfgoasdjg;lsAJG;alsjg;LSJGA;LDSFJG;SDLFJGSLD;FJG;LKSDFJG",
    "opasjcvihawufnasdfnopqphqnsqpqhwe9phnfpqshdv9upqhfpqnsdv9puqhwfhupsqdhvfqpojsdbnhiouqhfpqwhpqwhuhq",
    "ojqw0sfd mjwfvnifviojqjm je qhenw qfew qpwef qewfnw qophwefq weqwef uwqeipf sdf piuowqefpoh wqh eh",
    "ASODJF OASIHJDFIOSJD FJSADF PASDJNFPOIASJ JASDFJIASJFIAPSDF IASDJF JAIOSD ASJDFASIOFJ IAJD AO JIOA",
    "jasldkjfaspl;djfa;sljg;ldfjgodwfhodfhldfadlfgoasdjg;lsAJG;alsjg;LSJGA;LDSFJG;SDLFJGSLD;FJG;LKSDFJG",
    "opasjcvihawufnasdfnopqphqnsqpqhwe9phnfpqshdv9upqhfpqnsdv9puqhwfhupsqdhvfqpojsdbnhiouqhfpqwhpqwhuhq",
    "ojqw0sfd mjwfvnifviojqjm je qhenw qfew qpwef qewfnw qophwefq weqwef uwqeipf sdf piuowqefpoh wqh eh",
    "ASODJF OASIHJDFIOSJD FJSADF PASDJNFPOIASJ JASDFJIASJFIAPSDF IASDJF JAIOSD ASJDFASIOFJ IAJD AO JIOA",
    "jasldkjfaspl;djfa;sljg;ldfjgodwfhodfhldfadlfgoasdjg;lsAJG;alsjg;LSJGA;LDSFJG;SDLFJGSLD;FJG;LKSDFJG",
    "opasjcvihawufnasdfnopqphqnsqpqhwe9phnfpqshdv9upqhfpqnsdv9puqhwfhupsqdhvfqpojsdbnhiouqhfpqwhpqwhuhq",
    "ojqw0sfd mjwfvnifviojqjm je qhenw qfew qpwef qewfnw qophwefq weqwef uwqeipf sdf piuowqefpoh wqh eh",
    "ASODJF OASIHJDFIOSJD FJSADF PASDJNFPOIASJ JASDFJIASJFIAPSDF IASDJF JAIOSD ASJDFASIOFJ IAJD AO JIOA",
    "jasldkjfaspl;djfa;sljg;ldfjgodwfhodfhldfadlfgoasdjg;lsAJG;alsjg;LSJGA;LDSFJG;SDLFJGSLD;FJG;LKSDFJG",
    "opasjcvihawufnasdfnopqphqnsqpqhwe9phnfpqshdv9upqhfpqnsdv9puqhwfhupsqdhvfqpojsdbnhiouqhfpqwhpqwhuhq",
    "ojqw0sfd mjwfvnifviojqjm je qhenw qfew qpwef qewfnw qophwefq weqwef uwqeipf sdf piuowqefpoh wqh eh",
    "ASODJF OASIHJDFIOSJD FJSADF PASDJNFPOIASJ JASDFJIASJFIAPSDF IASDJF JAIOSD ASJDFASIOFJ IAJD AO JIOA",
    "jasldkjfaspl;djfa;sljg;ldfjgodwfhodfhldfadlfgoasdjg;lsAJG;alsjg;LSJGA;LDSFJG;SDLFJGSLD;FJG;LKSDFJG",
    "opasjcvihawufnasdfnopqphqnsqpqhwe9phnfpqshdv9upqhfpqnsdv9puqhwfhupsqdhvfqpojsdbnhiouqhfpqwhpqwhuhq",
    "ojqw0sfd mjwfvnifviojqjm je qhenw qfew qpwef qewfnw qophwefq weqwef uwqeipf sdf piuowqefpoh wqh eh",
    "ASODJF OASIHJDFIOSJD FJSADF PASDJNFPOIASJ JASDFJIASJFIAPSDF IASDJF JAIOSD ASJDFASIOFJ IAJD AO JIOA",
    "jasldkjfaspl;djfa;sljg;ldfjgodwfhodfhldfadlfgoasdjg;lsAJG;alsjg;LSJGA;LDSFJG;SDLFJGSLD;FJG;LKSDFJG",
    "opasjcvihawufnasdfnopqphqnsqpqhwe9phnfpqshdv9upqhfpqnsdv9puqhwfhupsqdhvfqpojsdbnhiouqhfpqwhpqwhuhq",
    "ojqw0sfd mjwfvnifviojqjm je qhenw qfew qpwef qewfnw qophwefq weqwef uwqeipf sdf piuowqefpoh wqh eh",
    "ASODJF OASIHJDFIOSJD FJSADF PASDJNFPOIASJ JASDFJIASJFIAPSDF IASDJF JAIOSD ASJDFASIOFJ IAJD AO JIOA",
    "jasldkjfaspl;djfa;sljg;ldfjgodwfhodfhldfadlfgoasdjg;lsAJG;alsjg;LSJGA;LDSFJG;SDLFJGSLD;FJG;LKSDFJG",
    "opasjcvihawufnasdfnopqphqnsqpqhwe9phnfpqshdv9upqhfpqnsdv9puqhwfhupsqdhvfqpojsdbnhiouqhfpqwhpqwhuhq",
    "ojqw0sfd mjwfvnifviojqjm je qhenw qfew qpwef qewfnw qophwefq weqwef uwqeipf sdf piuowqefpoh wqh eh",
    "ASODJF OASIHJDFIOSJD FJSADF PASDJNFPOIASJ JASDFJIASJFIAPSDF IASDJF JAIOSD ASJDFASIOFJ IAJD AO JIOA",
    "jasldkjfaspl;djfa;sljg;ldfjgodwfhodfhldfadlfgoasdjg;lsAJG;alsjg;LSJGA;LDSFJG;SDLFJGSLD;FJG;LKSDFJG",
    "opasjcvihawufnasdfnopqphqnsqpqhwe9phnfpqshdv9upqhfpqnsdv9puqhwfhupsqdhvfqpojsdbnhiouqhfpqwhpqwhuhq",
    "ojqw0sfd mjwfvnifviojqjm je qhenw qfew qpwef qewfnw qophwefq weqwef uwqeipf sdf piuowqefpoh wqh eh",
    "ASODJF OASIHJDFIOSJD FJSADF PASDJNFPOIASJ JASDFJIASJFIAPSDF IASDJF JAIOSD ASJDFASIOFJ IAJD AO JIOA",
    "jasldkjfaspl;djfa;sljg;ldfjgodwfhodfhldfadlfgoasdjg;lsAJG;alsjg;LSJGA;LDSFJG;SDLFJGSLD;FJG;LKSDFJG",
};